all:
  hosts:
    ml_host:
      ansible_host: <YOUR_VM_PUBLIC_IP>
      ansible_user: zodiac
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # Adjust path to your key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
