name: "Infrastructure apply"

on:
  workflow_dispatch:  # Запуск по кнопке
  push:
    branches:
      - project-work
    paths:
      - 'infra/**'

env:
  TF_ROOT: infra/terraform
  # Провайдеру Yandex нужны эти переменные напрямую или через TF_VAR
  TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
  TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
  TF_VAR_zone: ${{ secrets.ZONE }}
  TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
  TF_VAR_minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Restore .env from secret (base64)
        run: |
          echo "${{ secrets.DOTENV_B64 }}" | base64 --decode > infra/.env
          chmod 600 infra/.env

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          cat <<EOF > backend.conf
          access_key                  = "${{ secrets.MINIO_ACCESS_KEY }}"
          secret_key                  = "${{ secrets.MINIO_SECRET_KEY }}"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          skip_requesting_account_id  = true
          skip_s3_checksum            = true
          EOF
          terraform init -backend-config=backend.conf

      - name: Terraform Validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan -out=tfplan

      - name: Install Ansible and SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openssh-client
          pip3 install ansible

      - name: Setup SSH private key for Ansible
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > $HOME/.ssh/otus
          chmod 600 $HOME/.ssh/otus

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/project-work') && github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -auto-approve tfplan
