name: "Infrastructure Destroy"

on:
  workflow_dispatch:  # Только ручной запуск по кнопке

env:
  TF_ROOT: infra
  YC_TOKEN: ${{ secrets.YC_TOKEN }}
  YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
  TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
  TF_VAR_admin_password: ${{ secrets.TF_VAR_ADMIN_PASSWORD }}
  TF_VAR_bucket_name: ${{ vars.TF_VAR_BUCKET_NAME }}
  

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          cat <<EOF > backend.conf
          access_key                  = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_key                  = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          skip_requesting_account_id  = true
          skip_s3_checksum            = true
          EOF
          terraform init -backend-config=backend.conf

      - name: Terraform Destroy
        working-directory: ${{ env.TF_ROOT }}
        run: terraform destroy -auto-approve
