name: "Infrastructure Destroy"

on:
  workflow_dispatch:  # Только ручной запуск по кнопке

env:
  TF_ROOT: infra/terraform
  TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
  TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
  TF_VAR_zone: ${{ secrets.ZONE }}
  TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
  TF_VAR_minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
  

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: [self-hosted, MLOps-runner]
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          cat <<EOF > backend.conf
          access_key                  = "${{ secrets.MINIO_ACCESS_KEY }}"
          secret_key                  = "${{ secrets.MINIO_SECRET_KEY }}"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          skip_requesting_account_id  = true
          skip_s3_checksum            = true
          EOF
          terraform init -backend-config=backend.conf

      - name: Terraform Destroy
        working-directory: ${{ env.TF_ROOT }}
        run: terraform destroy -auto-approve
