name: "Infrastructure Destroy"

on:
  workflow_dispatch:  # Только ручной запуск по кнопке

env:
  TF_ROOT: infra/terraform
  YC_TOKEN: ${{ secrets.YC_TOKEN }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  zone: ${{ secrets.ZONE }}
  public_key: ${{ secrets.PUBLIC_KEY }}
  private_key: ${{ secrets.PRIVATE_KEY }}
  minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
  minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
  

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          cat <<EOF > backend.conf
          access_key                  = "${{ secrets.minio_access_key }}"
          secret_key                  = "${{ secrets.minio_secret_key }}"
          cloud_id                    = "${{ secrets.CLOUD_ID }}"
          folder_id                   = "${{ secrets.FOLDER_ID }}"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          skip_requesting_account_id  = true
          skip_s3_checksum            = true
          EOF
          terraform init -backend-config=backend.conf

      - name: Terraform Destroy
        working-directory: ${{ env.TF_ROOT }}
        run: terraform destroy -auto-approve
