name: "Infrastructure apply"

on:
  workflow_dispatch:  # Запуск по кнопке
  push:
    branches:
      - project-work
    paths:
      - 'infra/**'

env:
  TF_ROOT: infra/terraform
  # Провайдеру Yandex нужны эти переменные напрямую или через TF_VAR
  YC_TOKEN: ${{ secrets.YC_TOKEN }}
  CLOUD_ID: ${{ secrets.CLOUD_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  zone: ${{ secrets.ZONE }}
  public_key: ${{ secrets.PUBLIC_KEY }}
  private_key: ${{ secrets.PRIVATE_KEY }}
  minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
  minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
  bucket_name: ${{ vars.BUCKET_NAME }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          cat <<EOF > backend.conf
          access_key                  = "${{ secrets.minio_access_key }}"
          secret_key                  = "${{ secrets.minio_secret_key }}"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          skip_requesting_account_id  = true
          skip_s3_checksum            = true
          EOF
          terraform init -backend-config=backend.conf

      - name: Terraform Validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/project-work') && github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -auto-approve tfplan
