name: "Infrastructure apply"

on:
  workflow_dispatch:  # Запуск по кнопке
  push:
    branches:
      - project-work
    paths:
      - 'infra/**'

env:
  TF_ROOT: infra
  # Провайдеру Yandex нужны эти переменные напрямую или через TF_VAR
  YC_TOKEN: ${{ secrets.YC_TOKEN }}
  YC_CLOUD_ID: ${{ secrets.CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.FOLDER_ID }}
  # Маппинг секретов в переменные Terraform (TF_VAR_*)
  TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
  TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
  TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
  TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
  TF_VAR_cluster_name: ${{ secrets.CLUSTER_NAME }}
  TF_VAR_zone: ${{ secrets.ZONE }}
  TF_VAR_create_network: ${{ secrets.CREATE_NETWORK }}
  TF_VAR_network_id: ${{ secrets.NETWORK_ID }}
  TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_git_repo_url: ${{ github.server_url }}/${{ github.repository }}.git

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: |
          cat <<EOF > backend.conf
          access_key                  = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          secret_key                  = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          skip_requesting_account_id  = true
          skip_s3_checksum            = true
          EOF
          terraform init -backend-config=backend.conf

      - name: Terraform Validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/project-work') && github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -auto-approve tfplan
